version: '3'
services:
  # Laravel
  laravel-app:
    build:
      context: ./app-laravel
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - ./app-laravel:/var/www/html
    depends_on:
      - mysql-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: root

  # React
  react-app:
    build:
      context: ./app-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app-react:/app
    environment:
      REACT_APP_API_URL: "http://laravel-app:8002/api"  # Adjust the URL accordingly

  # MySQL
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
